In [6]:
import pandas as pd

In [7]:
df=pd.read_csv('train.csv')

In [8]:
import os
import pandas as pd
import tensorflow as tf
import numpy as np


In [9]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [10]:
df.iloc[0]['comment_text']

"Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

In [11]:
from tensorflow.keras.layers import TextVectorization


In [12]:
df['comment_text']

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [13]:
df[df.columns[2:]].values

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [14]:
x = df['comment_text']
y = df[df.columns[2:]].values 


In [15]:
x

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [16]:
y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [17]:
MAX_FEATURES=20000

In [18]:
vectorizer = TextVectorization(max_tokens=MAX_FEATURES,
                               output_sequence_length=1200,
                               output_mode='int')

In [19]:
#x.values


In [20]:
vectorizer.adapt(x.values)

In [21]:
vectorizer('hello girl you look bad')[:5] #here it hsows the words being converted into numbers

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([ 286, 1962,    7,  147,  337], dtype=int64)>

In [22]:
vectorized_text = vectorizer(x.values)


In [23]:
type(vectorized_text)

tensorflow.python.framework.ops.EagerTensor

In [24]:
vectorized_text

<tf.Tensor: shape=(159571, 1200), dtype=int64, numpy=
array([[ 643,   76,    2, ...,    0,    0,    0],
       [   1,   54, 2506, ...,    0,    0,    0],
       [ 425,  440,   70, ...,    0,    0,    0],
       ...,
       [   1, 7329,  383, ...,    0,    0,    0],
       [   5,   12,  533, ...,    0,    0,    0],
       [   5,    8,  130, ...,    0,    0,    0]], dtype=int64)>

In [25]:
len(x)

159571

In [26]:
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text,y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8)

In [27]:
dataset.as_numpy_iterator().next()

(array([[    7, 15754,     2, ...,     0,     0,     0],
        [  103,    85,    76, ...,     0,     0,     0],
        [   21, 16644,     9, ...,     0,     0,     0],
        ...,
        [  283,  1055,   563, ...,     0,     0,     0],
        [   76,   590,     7, ...,     0,     0,     0],
        [ 1126,    41,    35, ...,     0,     0,     0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

In [28]:
len(dataset) #number of batches

9974

In [29]:
#so previously we've divided our dataset into batches of 16, means in the array, 
#one element be having 16 sub-elements, and there wull be 9974 such elements. 159571/9947=16

In [30]:
int(len(dataset)*.7) #its just an exampler illustration

6981

In [31]:
train = dataset.take(int(len(dataset)*.7))

In [32]:
valid = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2))

In [33]:
test = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))

In [34]:
from tensorflow.keras.models import Sequential #method for buliding up this model

In [35]:
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional,Dense, Embedding

In [36]:
model = Sequential()
#creating embedding layer. Embedding means-like the information or charateristics or something about something it knows
#and me train the deep neural network through embedding. So we gonna creat an embedding layer. describing it following:
model.add(Embedding(MAX_FEATURES+1,32))
#creating an LSTM layer, having 32 lstm units, and using tanh, bcz, the gpu accelaration required for the lstm layout need to be tanh,
#dictated by tensorflow
model.add(Bidirectional(LSTM(32, activation='tanh')))

In [37]:
model.add(Dense(128,activation='relu'))
model.add(Dense(256,activation='relu'))
model.add(Dense(128,activation='relu'))

In [38]:
# this is our final layer and this final layer maps to the number
#of different outputs that we've got inside of our neural networks remember if we take a look at our y values
model.add(Dense(6,activation='sigmoid'))

In [39]:
model.compile(loss='BinaryCrossentropy', optimizer='Adam')


In [40]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          640032    
                                                                 
 bidirectional (Bidirectiona  (None, 64)               16640     
 l)                                                              
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

In [ ]:
history = model.fit(train, epochs=1, validation_data=valid)

 825/6981 [==>...........................] - ETA: 1:15:22 - loss: 0.1057

In [ ]:
input_text = vectorizer('you better die moron') 

In [ ]:
batch_X, batch_y = test.as_numpy_iterator().next()


In [ ]:
(model.predict(batch_X) > 0.5).astype(int)


In [2]:
it2 = np.expand_dims(input_text,0)

NameError: name 'np' is not defined

In [ ]:
res = model.predict(it2)

In [ ]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [ ]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [ ]:
for batch in test.as_numpy_iterator():
    X_true, y_true = batch
    yhat = model.predict(X_true)
    
    y_true = y_true.flatten()
    yhat = yhat.flatten()
    
    pre.update_state(y_true,yhat)
    re.update_state(y_true,yhat)
    acc.update_state(y_true,yhat)

In [ ]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')


In [ ]:
!pip install gradio jinja2

In [ ]:
import tensorflow as tf
import gradio as gr

In [ ]:
model.save('toxicity.h5')

In [1]:
model = tf.keras.models.load_model('toxicity.h5')


NameError: name 'tf' is not defined

In [ ]:
input_str = vectorizer('alright go to hell!')


In [ ]:
res = model.predict(np.expand_dims(input_str,0))

In [ ]:
res 

In [ ]:
def score_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = model.predict(vectorized_comment)
    
    text = ''
    for idx, col in enumerate(df.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx]>0.5)
    
    return text

In [ ]:
interface = gr.Interface(fn=score_comment, 
                         inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
                        outputs='text')

In [ ]:
interface.launch(share=True)